[package]
name = "rustside"
version = "0.1.0"
authors = ["Dmitriy Sokolov <silentsokolov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
url = "2.2.2"
jni = { version = "0.19", features = ["invocation"] }

[profile.dev]
split-debuginfo = "unpacked"
