/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_silentsokolov_App */

#ifndef _Included_com_github_silentsokolov_App
#define _Included_com_github_silentsokolov_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_silentsokolov_App
 * Method:    nativeUDF
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_silentsokolov_App_nativeUDF
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
