name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_rust:
    name: Build rust on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: Linux
            os: ubuntu-latest
            type: linux-amd64
            ext: so
          - build: macOS
            os: macOS-latest
            type: darwin-amd64
            ext: dylib

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'

      - name: Build
        run: |
          make rust_build
          make copy_rust_to_java

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib_${{ matrix.type }}
          path: '**/${{ matrix.type }}.${{ matrix.ext }}'
          retention-days: 1
  
  build_jar:
    name: Build jar
    needs: [build_rust]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8.0'

      - name: Download linux artifact
        uses: actions/download-artifact@v2
        with:
          name: lib_linux-amd64

      - name: Download darwin artifact
        uses: actions/download-artifact@v2
        with:
          name: lib_darwin-amd64

      - name: Build
        run: |
          make java_package
          make copy_jar

      - name: Attach to release
        uses: softprops/action-gh-release@v1
        with:
          files: '**/${{ github.event.repository.name }}.jar'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
